model:
  name: "ProtoCrossDomainSampling"
  notes: "with no photo / CrossEntropyLoss / test shot=1 / train shot=1"
  params:
    embedding_extractor:
      backbone: "block5"
      channel_size: 512
      

checkpoint:
  save_dir: "./checkpoint/proto_cross_domain_sampling.example/"
  load_path: "./checkpoint/proto_cross_domain_sampling.example/ProtoCrossDomainSamplingTrainer.checkpoint.pkl"


cuda:
  id: 0


modes:
  train:
    total_step: 30000
    report_step: 200
    save_step: 5000
    start_val_step: 5000
    val_step: 200
    optimizer: "SGD"
    lr: 0.0005
    warmup_period: 3000
    way: 5
    shot: 1
    input_image_size: 64
    train_batch_size: 1
    augmentations:
      false
      # - "RandomResizedCrop"
      # - "RandomAffine"
      # - "RandomRotation"
      # - "ColorJitter"
      # - "RandomHorizontalFlip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/mini-imagenet/"
        meta: "./data/meta/miniimagenet_1_shot.meta.json"
      target:
        - ""

  resume:
    total_step: 40000
    report_step: 200
    save_step: 5000
    start_val_step: 5000
    val_step: 200
    optimizer: "SGD"
    lr: 0.0005
    warmup_period: 3000
    way: 5
    shot: 1
    input_image_size: 64
    train_batch_size: 1
    augmentations:
      false
      # - "RandomResizedCrop"
      # - "RandomAffine"
      # - "RandomRotation"
      # - "ColorJitter"
      # - "RandomHorizontalFlip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/mini-imagenet/"
        meta: "./data/meta/miniimagenet_1_shot.meta.json"
      target:
        - ""

  eval:
    domain_dataset:
      root_dir: ""
      target:
        - ""
