model:
  name: "ProtoIdenticalDomainSampling"
  notes: ""
  params:
    embedding_extractor:
      channel_size: 512


checkpoint:
  save_dir: "./checkpoint/proto_identical_domain_sampling.example/"
  load_path: "./checkpoint/proto_identical_domain_sampling.example/ProtoIdenticalDomainSamplingTrainer.checkpoint.pkl"


cuda:
  id: 1


modes:
  train:
    total_step: 20000
    report_step: 100
    save_step: 2000
    val_step: 400
    optimizer: "SGD"
    lr: 0.0005
    warmup_period: 3000
    way: 5
    shot: 5
    input_image_size: 64
    train_batch_size: 1
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/mini-imagenet/"
        meta: "./data/meta/miniimagenet.meta.json"
      target:
        - ""

  resume:
    total_step: 40000
    report_step: 100
    save_step: 2000
    val_step: 400
    optimizer: "SGD"
    lr: 0.0005
    warmup_period: 3000
    way: 5
    shot: 5
    input_image_size: 64
    train_batch_size: 1
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/mini-imagenet/"
        meta: "./data/meta/miniimagenet.meta.json"
      target:
        - ""

  eval:
    domain_dataset:
      root_dir: ""
      target:
        - ""
