model:
  name: "ProtoIdenticalDomainSampling"
  notes: "CrossEntropyLoss / test shot=5 / train shot=5"
  params:
    embedding_extractor:
      backbone: "block5"
      channel_size: 512


checkpoint:
  save_dir: "./checkpoint/proto_identical_domain_sampling.example/"
  load_path: "./checkpoint/proto_identical_domain_sampling.example/ProtoIdenticalDomainSampling.checkpoint.pkl"


cuda:
  id: 1


modes:
  train:
    total_step: 30000
    report_step: 200
    save_step: 5000
    start_val_step: 5000
    val_step: 500
    optimizer: "SGD"
    lr: 0.0005
    warmup_period: 3000
    way: 5
    shot: 5
    input_image_size: 84
    train_batch_size: 1
    augmentations:
      false
      # - "RandomResizedCrop"
      # - "RandomAffine"
      # - "RandomRotation"
      # - "ColorJitter"
      # - "RandomHorizontalFlip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/mini-imagenet/"
        meta: "./data/meta/miniimagenet_5_shot.meta.json"
      target:
        - ""

  resume:
    total_step: 40000
    report_step: 200
    save_step: 2000
    start_val_step: 5000
    val_step: 500
    optimizer: "SGD"
    lr: 0.0005
    warmup_period: 1
    way: 5
    shot: 5
    input_image_size: 84
    train_batch_size: 1
    augmentations:
      false
      # - "RandomResizedCrop"
      # - "RandomAffine"
      # - "RandomRotation"
      # - "ColorJitter"
      # - "RandomHorizontalFlip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/mini-imagenet/"
        meta: "./data/meta/miniimagenet_5_shot.meta.json"
      target:
        - ""

  eval:
    domain_dataset:
      root_dir: ""
      target:
        - ""
