model:
  name: "RelCrossDomainSampling"
  notes: "test shot=5 / train shot=5"
  params:
    embedding_extractor:
      backbone: "block5"
      channel_size: 256


checkpoint:
  save_dir: "./checkpoint/rel_cross_domain_sampling.example/"
  load_path: "./checkpoint/rel_cross_domain_sampling.example/RelCrossDomainSamplingTrainer.checkpoint.pkl"


cuda:
  id: 0


modes:
  train:
    total_step: 30000
    report_step: 200
    save_step: 5000
    start_val_step: 10000
    val_step: 500
    optimizer: "Adam"
    lr: 0.001
    warmup_period: 1000
    way: 5
    shot: 5
    input_image_size: 64
    train_batch_size: 1
    augmentations:
      false
      # - "RandomResizedCrop"
      # - "RandomAffine"
      # - "RandomRotation"
      # - "ColorJitter"
      # - "RandomHorizontalF1lip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/mini-imagenet/"
        meta: "./data/meta/miniimagenet_5_shot.meta.json"
      target:
        - ""

  resume:
    total_step: 40000
    report_step: 200
    save_step: 5000
    start_val_step: 10000
    val_step: 1
    optimizer: "Adam"
    lr: 0.0005
    warmup_period: 10000
    way: 5
    shot: 5
    input_image_size: 64
    train_batch_size: 1
    augmentations:
      false
      # - "RandomResizedCrop"
      # - "RandomAffine"
      # - "RandomRotation"
      # - "ColorJitter"
      # - "RandomHorizontalF1lip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/mini-imagenet/"
        meta: "./data/meta/miniimagenet_5_shot.meta.json"
      target:
        - ""

  eval:
    domain_dataset:
      root_dir: ""
      target:
        - ""
