model:
  name: "RelCrossDomainSampling"
  notes: "test shot=5 / train shot=5 / aug"
  params:
    embedding_extractor:
      backbone: "block5"
      channel_size: 512


checkpoint:
  save_dir: "./checkpoint/rel_cross_domain_sampling.example/"
  load_path: "./checkpoint/rel_cross_domain_sampling.example/RelCrossDomainSamplingTrainer.checkpoint.pkl"


cuda:
  id: 0


modes:
  train:
    total_step: 110000
    report_step: 200
    save_step: 5000
    start_val_step: 30000
    val_step: 1000
    optimizer: "SGD"
    lr_extractor: 0.1
    lr_relation: 0.0005
    warmup_period: 3000
    way: 5
    shot: 5
    input_image_size: 64
    train_batch_size: 1
    augmentations:
      # false
      # - "RandomResizedCrop"
      - "RandomAffine"
      - "RandomRotation"
      # - "ColorJitter"
      - "RandomHorizontalFlip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/omniglot/"
        meta: "./data/meta/omniglot_5_shot.meta.json"
      target:
        - ""

  resume:
    total_step: 110000
    report_step: 200
    save_step: 5000
    start_val_step: 30000
    val_step: 1000
    optimizer: "SGD"
    lr: 0.1
    lr_2: 0.0005
    warmup_period: 3000
    way: 5
    shot: 5
    input_image_size: 64
    train_batch_size: 1
    augmentations:
      # false
      # - "RandomResizedCrop"
      - "RandomAffine"
      - "RandomRotation"
      # - "ColorJitter"
      - "RandomHorizontalFlip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/omniglot/"
        meta: "./data/meta/omniglot_5_shot.meta.json"
      target:
        - ""

  eval:
    domain_dataset:
      root_dir: ""
      target:
        - ""
