model:
  name: "RelCrossDomainSampling"
  notes: "test shot=1 / train shot=1"
  params:
    embedding_extractor:
      backbone: "block5"
      channel_size: 128


checkpoint:
  save_dir: "./checkpoint/rel_cross_domain_sampling.example/"
  load_path: "./checkpoint/rel_cross_domain_sampling.example/RelCrossDomainSamplingTrainer.checkpoint.pkl"


cuda:
  id: 1


modes:
  train:
    total_step: 25000
    report_step: 200
    save_step: 5000
    start_val_step: 5000
    val_step: 500
    optimizer: "SGD"
    lr: 0.05
    warmup_period: 3000
    way: 5
    shot: 1
    input_image_size: 64
    train_batch_size: 1
    augmentations:
      false
      # - "RandomResizedCrop"
      # - "RandomAffine"
      # - "RandomRotation"
      # - "ColorJitter"
      # - "RandomHorizontalF1lip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/omniglot/"
        meta: "./data/meta/omniglot_1_shot.meta.json"
      target:
        - ""

  resume:
    total_step: 25000
    report_step: 200
    save_step: 5000
    start_val_step: 5000
    val_step: 500
    optimizer: "SGD"
    lr: 0.05
    warmup_period: 3000
    way: 5
    shot: 1
    input_image_size: 64
    train_batch_size: 1
    augmentations:
      false
      # - "RandomResizedCrop"
      # - "RandomAffine"
      # - "RandomRotation"
      # - "ColorJitter"
      # - "RandomHorizontalF1lip"
    domain_dataset:
      source:
        root_dir: "./data/PACS/kfold"
        meta:
          # - "./data/meta/photo.meta.json"
          - "./data/meta/art_painting.meta.json"
          - "./data/meta/cartoon.meta.json"
          - "./data/meta/sketch.meta.json"
      val:
        root_dir: "./data/omniglot/"
        meta: "./data/meta/omniglot_1_shot.meta.json"
      target:
        - ""

  eval:
    domain_dataset:
      root_dir: ""
      target:
        - ""
